### PR TITLE
Silently ignore matches at the end

### PR DESCRIPTION
**Pull request by s3bk**
I hit the case of `index == text.len()` a bit.

### CODE REVIEW

**Comment by bminixhofer** [comment]
Oof, that's quite bad. Thanks for the PR! At the risk of being nitpicky, I'd like to be a bit more explicit here, e. g.:

```rust
if index == text.len() {
    continue;
}

if mask[index].is_none() {
    mask[index] = Some(rule.do_break());
}
```

Also, please add a test. Locally I found that this reproduces the error:

```rust
    #[test]
    fn ignores_last_match_index() {
        let rules =
            SRX::from_str(&fs::read_to_string("data/segment.srx").expect("example file exists"))
                .expect("example file is valid")
                .language_rules("en");

        rules.split("Hello! ");
    }
```

Thanks!

**Comment by s3bk** [comment]
Would `if index >= text.len()` work?
Just thinking of funny cases…

**Comment by bminixhofer** [comment]
Sure, we can do that.

**Comment by bminixhofer** [comment]
LGTM. Thanks!

**Comment by bminixhofer** [comment]
I released a patch `0.1.2` including this fix.

**Pull request merged**
